import os
import requests
import time
import logging
from ..utils.parser import parse_ai_response

logger = logging.getLogger(__name__)

def generate_code_review(code: str, language: str):
    """
    Calls the AI API to generate a code review.
    Handles retries, timeouts, and parses the response.
    """
    api_key = os.environ.get("GEMINI_API_KEY")
    if not api_key or api_key == "your_api_key_here":
        # Fallback for local UI testing
        from ..schemas.review import ReviewResponse, ReviewIssue
        issue = ReviewIssue(
            severity="warning",
            message="No API Key detected.",
            suggestion="Set GEMINI_API_KEY in the backend/.env file to enable real AI code reviews.",
            line=1
        )
        return ReviewResponse(score=80, issues=[issue], summary="Running in local UI preview mode.")

    prompt = f"""
    Perform a professional, deep-dive code review of the following {language} code.
    Identify any syntax errors, anti-patterns, security vulnerabilities, or performance bottlenecks.

    Code to review:
    ```{language}
    {code}
    ```
    """

    # FIX: Changed to "gemini-2.5-flash" because it has a generous 
    # free tier without needing a billing account, bypassing the limit: 0 error.
    model_name = "gemini-2.5-flash"
    
    # SECURITY UPDATE: Removed the API key from the URL query parameters.
    url = f"https://generativelanguage.googleapis.com/v1beta/models/{model_name}:generateContent"
    
    # SECURITY UPDATE: Passing the API key via the x-goog-api-key header instead.
    # This prevents the API key from leaking into network logs, proxy logs, or URL history.
    headers = {
        "Content-Type": "application/json",
        "x-goog-api-key": api_key
    }
    
    payload = {
        "contents": [{
            "parts": [{"text": prompt}]
        }],
        # Upgraded System Instructions to enforce crisp, UI-friendly JSON output
        "systemInstruction": {
            "parts": [{"text": """You are an elite software architect and automated code reviewer.
Your goal is to provide crisp, highly actionable, and precise feedback designed to be displayed in a premium UI dashboard.

Respond ONLY with a valid JSON object matching this exact schema: 
{"score": <0-100 int>, "summary": "<string>", "issues": [{"severity": "info|warning|error", "message": "<string>", "suggestion": "<string>", "line": <int or null>}]}

Guidelines for UI presentation:
- 'score': 0-100. 100 means perfect, 0 means critically broken.
- 'summary': Provide a punchy, professional 1-2 sentence executive summary of the code's state. 
- 'message': Keep the issue title/message extremely concise and specific (e.g., 'IndentationError: unexpected indent').
- 'suggestion': Provide a clear, direct instruction on how to fix the issue. Avoid fluff and pleasantries.
- 'severity': Strictly use 'error' (for broken code/bugs), 'warning' (for code smells/performance), or 'info' (for nitpicks/style)."""}]
        },
        "generationConfig": {
            "temperature": 0.2,
            "responseMimeType": "application/json" # Forces the API to return pure JSON without markdown code blocks
        }
    }

    max_retries = 3
    timeout_seconds = 30

    for attempt in range(max_retries):
        try:
            response = requests.post(url, headers=headers, json=payload, timeout=timeout_seconds)
            
            # This will raise an HTTPError for 400, 500, etc.
            response.raise_for_status()
            
            data = response.json()
            # Extract text from Gemini response format
            candidates = data.get('candidates', [])
            if not candidates:
                raise ValueError("No content generated by AI.")
                
            raw_text = candidates[0].get('content', {}).get('parts', [{}])[0].get('text', '')
            
            # Pass the raw text to our parser directly here
            return parse_ai_response(raw_text)
            
        except requests.exceptions.HTTPError as e:
            # Extract the actual API error message sent back by Google
            api_error_details = e.response.text 
            
            # Try to parse the Google API JSON error format to extract just the message
            clean_error_msg = api_error_details
            try:
                error_data = e.response.json()
                if "error" in error_data and "message" in error_data["error"]:
                    clean_error_msg = error_data["error"]["message"]
            except ValueError:
                pass # Fall back to the raw string if it's not JSON
                
            error_str = str(e).replace(api_key, "HIDDEN_API_KEY") if api_key else str(e)
            
            logger.error(f"AI API HTTP error: {error_str} | Google API Details: {clean_error_msg}")
            
            # Stop immediately on 400 Bad Request since retrying won't fix syntax/model/auth errors
            if response.status_code == 400:
                 raise RuntimeError(f"AI API Bad Request: {clean_error_msg}")
            
            if attempt == max_retries - 1:
                raise RuntimeError(f"AI API request failed: {error_str} - {clean_error_msg}")

        except requests.exceptions.Timeout:
            logger.warning(f"AI API timeout on attempt {attempt + 1}/{max_retries}")
            if attempt == max_retries - 1:
                raise RuntimeError("AI API timed out after maximum retries.")

        except requests.exceptions.RequestException as e:
            error_str = str(e).replace(api_key, "HIDDEN_API_KEY") if api_key else str(e)
            logger.error(f"AI API request failed: {error_str}")
            if attempt == max_retries - 1:
                raise RuntimeError(f"AI API request failed: {error_str}")

        except Exception as e:
            error_str = str(e).replace(api_key, "HIDDEN_API_KEY") if api_key else str(e)
            logger.error(f"Error during AI processing: {error_str}")
            if attempt == max_retries - 1:
                raise RuntimeError(f"AI analysis failed: {error_str}")
                
        # Exponential backoff
        time.sleep(2 ** attempt)
        
    raise RuntimeError("Failed to generate code review after retries.")